name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          #cache: maven

      - name: Check Java Version
        run: java -version 
    
      - name: Run a one-line echo
        run: echo hello, world!

      - name: secrets variales
        run: echo ${{secrets.SERVER_IP}}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts


      - name: SSH into server
        run: ssh -i ~/.ssh/id_rsa hpe@${{ secrets.SERVER_IP }} "echo Connected!"
      
